name: shelf_appengine
version: 0.3.0-dev
author: Dart Team <misc@dartlang.org>
description: Integration for the appengine and shelf packages
homepage: https://github.com/dart-lang/shelf_appengine
environment:
  sdk: '>=1.9.0 <2.0.0'
dependencies:
  appengine: ^0.4.0
  mime: ^0.9.0
  path: ^1.4.1
  shelf: ^0.6.0
  stack_trace: ^1.0.0
dev_dependencies:
  http: ^0.11.2
  scheduled_test: ^0.12.0
  test: ^0.12.0
